#!/bin/bash
set -e

APP_PASSWORD=$(cat /run/secrets/postgres_password)
READ_PASSWORD=$(cat /run/secrets/postgres_password)

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
    -- Create users
    CREATE USER $APP_USER WITH PASSWORD '$APP_PASSWORD';
    CREATE USER $READ_USER WITH PASSWORD '$READ_PASSWORD';
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
    -- Grant permissions
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $APP_USER;
    GRANT CREATE ON SCHEMA public TO $APP_USER;
    GRANT USAGE ON SCHEMA public TO $APP_USER;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $APP_USER;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO $APP_USER;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $APP_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $APP_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public 
        GRANT ALL PRIVILEGES ON TABLES TO $APP_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public 
        GRANT ALL PRIVILEGES ON SEQUENCES TO $APP_USER;

    -- Read user permissions
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO $READ_USER;
    GRANT USAGE ON SCHEMA public TO $READ_USER;
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO $READ_USER;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public 
        GRANT SELECT ON TABLES TO $READ_USER;
EOSQL