apiVersion: v1
kind: Service
metadata:
  labels:
    app: ec2-app
  name: backend-service
spec:
  type: ClusterIP
  selector:
    type: backend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
